import { expect, test, type Locator, type Page } from "@playwright/test";
test.setTimeout(120_000);
async function unit(page: Page, label: string): Promise<Locator> { await page.waitForSelector(`[data-psyflow-unit-label="${label}"]`, { state: "visible", timeout: 10_000 }); return page.locator(`[data-psyflow-unit-label="${label}"]`).first(); }
async function pressReplace(page: Page, target: Locator, key: string) { const handle = await target.elementHandle(); await page.keyboard.press(key); await page.waitForFunction((element) => !element?.isConnected, handle, { timeout: 5_000 }); }
async function squareSignature(target: Locator) { return target.locator(".psyflow-stage-stim").evaluateAll((nodes) => nodes.filter((node) => getComputedStyle(node).backgroundColor !== "rgba(0, 0, 0, 0)").map((node) => { const style = getComputedStyle(node); return `${style.left}|${style.top}|${style.backgroundColor}`; }).sort()); }
test("Visual Change Detection runs same/change trials and exports", async ({ page }) => { let patched = false; await page.route("**/*.yaml", async (route) => { const response = await route.fetch(), original = await response.text(), body = original.replace("scored_repetitions_per_cell: 20", "scored_repetitions_per_cell: 1").replace("fixation_duration: 0.5", "fixation_duration: 0.02").replace("memory_duration: 0.1", "memory_duration: 0.12").replace("retention_duration: 0.9", "retention_duration: 0.02").replace("response_window: 2.0", "response_window: 2.0"); patched = body.includes("scored_repetitions_per_cell: 1"); await route.fulfill({ response, body }); }); await page.goto("/?task=H000068-visual-change-detection-task"); await expect.poll(() => patched).toBeTruthy(); await page.locator('input[name="subject_id"]').fill("168"); await page.locator('#psyflow-task-form button[type="submit"]').click(); await page.locator("#psyflow-task-preflight .psyflow-task-button").click(); await pressReplace(page, await unit(page, "instruction"), "Space");
  for (let trial = 0; trial < 8; trial += 1) { const memory = await unit(page, "memory_array"), sample = await squareSignature(memory); const testUnit = await unit(page, "test_array"), probe = await squareSignature(testUnit); await pressReplace(page, testUnit, JSON.stringify(sample) === JSON.stringify(probe) ? "f" : "j"); }
  await pressReplace(page, await unit(page, "practice_summary"), "Space");
  for (let trial = 0; trial < 8; trial += 1) { const memory = await unit(page, "memory_array"), sample = await squareSignature(memory); const testUnit = await unit(page, "test_array"), probe = await squareSignature(testUnit); await pressReplace(page, testUnit, JSON.stringify(sample) === JSON.stringify(probe) ? "f" : "j"); }
  await pressReplace(page, await unit(page, "good_bye"), "Space"); await expect(page.locator("#psyflow-task-results")).toBeVisible(); const result = await page.evaluate(() => window.__PSYFLOW_WEB_LAST_RESULT__ ?? null); expect(result).not.toBeNull(); if (!result) return; expect(result.aborted).toBeFalsy(); const rows = result.reduced_rows as Array<Record<string, unknown>>; expect(rows).toHaveLength(16); expect(rows.filter((row) => row.is_practice === false)).toHaveLength(8); expect(new Set(rows.filter((row) => row.is_practice === false).map((row) => row.condition)).size).toBe(8); expect(rows.every((row) => row.correct === true)).toBeTruthy(); const download = page.waitForEvent("download"); await page.getByRole("button", { name: "Download reduced.csv" }).click(); expect((await download).suggestedFilename()).toBe("H000068-visual-change-detection-task_reduced.csv"); });
