import {describe,expect,it} from "vitest";
import {StimBank,TaskSettings,TrialBuilder,type RuntimeView,type TrialSnapshot} from "../../src";
import {run_trial} from "../../../H000066-fitts-law-pointing-task/src/run_trial";
import {generateTrialPlans} from "../../../H000066-fitts-law-pointing-task/src/utils";
describe("H000066 Fitts Law",()=>{
 it("builds 16 grouped cells with homing plus eight alternating movements",()=>{const p=generateTrialPlans(8,66066);expect(p).toHaveLength(144);expect(new Set(p.map(x=>x.condition)).size).toBe(16);for(const c of new Set(p.map(x=>x.condition))){const g=p.filter(x=>x.condition===c);expect(g.filter(x=>x.is_homing)).toHaveLength(1);expect(g.map(x=>x.active_side)).toEqual(["left","right","left","right","left","right","left","right","left"]);}});
 it("compiles framework-owned pointer acquisition and scores hit/timeout",()=>{const p=generateTrialPlans(1,66066)[1],s=TaskSettings.from_dict({target_height_deg:6,response_deadline:3}) as TaskSettings&Record<string,unknown>;s.triggers={map:{target_onset:20,target_hit:30,movement_complete:31,movement_timeout:32}};const b=new StimBank({target:{type:"rect",width:1,height:6,pos:[0,0]},center_marker:{type:"circle",radius:.1,pos:[0,0]}} as never),t=new TrialBuilder({trial_id:1,block_id:"pointing",trial_index:1,condition:p.condition});run_trial(t,p,{settings:s,stimBank:b});const c=t.build(),u=c.units[0];expect(u).toMatchObject({unit_label:"pointing_target",op:"capture_pointer_sequence",duration:3,onset_trigger:20});expect(u.pointer_cfg).toMatchObject({max_selections:1,complete_trigger:31,timeout_trigger:32});const finish=(state:Record<string,unknown>)=>{const out={...c.trial_state},units={pointing_target:state},snap={trial_id:1,block_id:"pointing",trial_index:1,condition:p.condition,units,trial_state:out} satisfies TrialSnapshot;c.finalizers[0](snap,{getReducedRows:()=>[],sumReducedField:()=>0} satisfies RuntimeView,{setTrialState:(k,v)=>{out[k]=v;},getUnitState:(l,k)=>units.pointing_target[k]});return out;};expect(finish({completed:true,rt:.45})).toMatchObject({outcome:"hit",movement_time:.45});expect(finish({completed:false,rt:null})).toMatchObject({outcome:"timeout",movement_time:null});});
});

