import { describe, expect, it } from "vitest";
import stimuliText from "../../../H000065-levels-of-processing-task/assets/stimuli.csv?raw";
import { StimBank, TaskSettings, TrialBuilder, parseCsvRows, type RuntimeView, type TrialSnapshot } from "../../src";
import { run_trial } from "../../../H000065-levels-of-processing-task/src/run_trial";
import { generateEncodingPlans, generateRecognitionPlans, validateItems, type Item, type TrialPlan } from "../../../H000065-levels-of-processing-task/src/utils";

function plans() { const items = validateItems(parseCsvRows<Item>(stimuliText)); const encoding = generateEncodingPlans(items, 10, 65065); return { items, encoding, recognition: generateRecognitionPlans(items, encoding, 120, 65065) }; }
function fixtures() { const settings = TaskSettings.from_dict({ question_duration: 2, word_duration: 0.2, encoding_response_duration: 1.8, recognition_duration: 3 }) as TaskSettings & Record<string, unknown>; settings.triggers = { map: { question_structural: 20, question_phonemic: 21, question_semantic: 22, encoding_word: 30, yes_response: 40, no_response: 41, encoding_timeout: 42, recognition_old: 50, recognition_new: 51, old_response: 60, new_response: 61, recognition_timeout: 62 } }; return { settings, stimBank: new StimBank({ question_structural: { type: "text", text: "case" }, question_phonemic: { type: "text", text: "{cue}" }, question_semantic: { type: "text", text: "{sentence}" }, word: { type: "text", text: "apple" }, fixation: { type: "text", text: "+" } } as never) }; }
function build(plan: TrialPlan) { const { settings, stimBank } = fixtures(); const trial = new TrialBuilder({ trial_id: 1, block_id: plan.phase, trial_index: 0, condition: plan.condition }); run_trial(trial, plan, { settings, stimBank }); return trial.build(); }
function finalize(compiled: ReturnType<typeof build>, units: TrialSnapshot["units"]) { const state: Record<string, unknown> = { ...compiled.trial_state }; const snapshot = { trial_id: compiled.trial_id, block_id: compiled.block_id, trial_index: 0, condition: compiled.condition, units, trial_state: state } satisfies TrialSnapshot; compiled.finalizers[0](snapshot, { getReducedRows: () => [], sumReducedField: () => 0 } satisfies RuntimeView, { setTrialState: (k, v) => { state[k] = v; }, getUnitState: (l, k) => units[l]?.[k] }); return state; }

describe("H000065 Levels of Processing", () => {
  it("preserves the exact six-cell encoding and 60-old/120-new recognition design", () => { const p = plans(); expect(p.encoding).toHaveLength(60); for (const level of ["structural", "phonemic", "semantic"]) for (const answer of ["yes", "no"]) expect(p.encoding.filter((x) => x.encoding_level === level && x.expected_answer === answer)).toHaveLength(10); expect(p.recognition).toHaveLength(180); expect(p.recognition.filter((x) => x.is_old)).toHaveLength(60); expect(new Set(p.recognition.map((x) => x.item_id)).size).toBe(180); });
  it("compiles source-aligned encoding and recognition timing", () => { const p = plans(); const e = build(p.encoding[0]); expect(e.units.find((u) => u.unit_label === "encoding_question")).toMatchObject({ op: "show", duration: 2 }); expect(e.units.find((u) => u.unit_label === "encoding_word")).toMatchObject({ op: "capture_response", duration: 0.2 }); expect(e.units.find((u) => u.unit_label === "encoding_response")).toMatchObject({ op: "capture_response", duration: 1.8 }); const r = build(p.recognition[0]); expect(r.units[0]).toMatchObject({ unit_label: "recognition_word", op: "capture_response", duration: 3 }); });
  it("scores old and new recognition outcomes", () => { const p = plans(); const old = build(p.recognition.find((x) => x.is_old)!); expect(finalize(old, { recognition_word: { response: "f", rt: 0.5 } })).toMatchObject({ outcome: "hit", correct: true }); expect(finalize(old, { recognition_word: { response: "j", rt: 0.6 } })).toMatchObject({ outcome: "miss", correct: false }); const fresh = build(p.recognition.find((x) => !x.is_old)!); expect(finalize(fresh, { recognition_word: { response: "f", rt: 0.7 } })).toMatchObject({ outcome: "false_alarm" }); expect(finalize(fresh, { recognition_word: { response: "j", rt: 0.8 } })).toMatchObject({ outcome: "correct_rejection" }); });
});

