import { describe, expect, it } from "vitest";
import { StimBank, TaskSettings, TrialBuilder, type RuntimeView, type TrialSnapshot } from "../../src";
import { run_trial } from "../../../H000068-visual-change-detection-task/src/run_trial";
import { SET_SIZES, generateTrialPlans, summarizeTrials, type TrialPlan } from "../../../H000068-visual-change-detection-task/src/utils";

function build(plan: TrialPlan) { const settings = TaskSettings.from_dict({ total_blocks: 1, total_trials: 1, trial_per_block: 1, conditions: [plan.condition], fixation_duration: .5, memory_duration: .1, retention_duration: .9, response_window: 2, square_size_deg: 1.25 }) as TaskSettings & Record<string, unknown>; settings.triggers = { map: { fixation: 20, memory_set_2: 22, memory_set_4: 24, memory_set_6: 26, memory_set_8: 28, retention: 30, test_same: 40, test_change: 41, same_response: 50, change_response: 51, response_timeout: 52 } }; const bank = new StimBank({ fixation: { type: "text", text: "+" }, color_square: { type: "rect", width: 1.25, height: 1.25 } }); const trial = new TrialBuilder({ trial_id: 1, block_id: "scored", trial_index: 0, condition: plan.condition }); run_trial(trial, plan, { settings, stimBank: bank }); return trial.build(); }
function finalize(compiled: ReturnType<typeof build>, response?: string) { const units: TrialSnapshot["units"] = { test_array: { response: response ?? null, rt: response ? .42 : null } }, state = { ...compiled.trial_state }; const snapshot = { trial_id: 1, block_id: "scored", trial_index: 0, condition: compiled.condition, units, trial_state: state } satisfies TrialSnapshot; compiled.finalizers[0](snapshot, { getReducedRows: () => [], sumReducedField: () => 0 } satisfies RuntimeView, { setTrialState: (k, v) => { state[k] = v; }, getUnitState: (label, key) => units[label]?.[key] }); return state; }

describe("H000068 visual change detection", () => {
  it("balances all cells and changes exactly one color without moving squares", () => { const plans = generateTrialPlans(3, 68068, false); expect(plans).toHaveLength(24); for (const size of SET_SIZES) for (const status of ["same", "change"]) expect(plans.filter((p) => p.set_size === size && p.change_status === status)).toHaveLength(3); plans.forEach((p) => { expect(new Set(p.memory_colors).size).toBe(p.set_size); expect(p.positions).toHaveLength(p.set_size); const differences = p.memory_colors.filter((color, i) => color !== p.test_colors[i]).length; expect(differences).toBe(p.change_status === "change" ? 1 : 0); expect(p.changed_index == null).toBe(p.change_status === "same"); }); });
  it("preserves phase timing, triggers, keys, and outcome semantics", () => { const change = generateTrialPlans(1, 68068, false).find((p) => p.change_status === "change")!; const compiled = build(change); expect(compiled.units.map((u) => u.unit_label)).toEqual(["fixation", "memory_array", "retention", "test_array"]); expect(compiled.units.find((u) => u.unit_label === "memory_array")).toMatchObject({ duration: .1, onset_trigger: 22 }); expect(compiled.units.find((u) => u.unit_label === "retention")).toMatchObject({ duration: .9, onset_trigger: 30 }); expect(compiled.units.find((u) => u.unit_label === "test_array")?.response_cfg).toMatchObject({ keys: ["f", "j"], correct_keys: ["j"], timeout_trigger: 52 }); expect(finalize(compiled, "j")).toMatchObject({ correct: true, outcome: "hit" }); expect(finalize(compiled, "f")).toMatchObject({ correct: false, outcome: "miss" }); expect(finalize(compiled)).toMatchObject({ correct: false, outcome: "timeout" }); });
  it("computes Cowan K from hits and false alarms", () => { const rows = [{ is_practice: false, set_size: 4, change_status: "change", outcome: "hit", correct: true }, { is_practice: false, set_size: 4, change_status: "change", outcome: "miss", correct: false }, { is_practice: false, set_size: 4, change_status: "same", outcome: "false_alarm", correct: false }, { is_practice: false, set_size: 4, change_status: "same", outcome: "correct_rejection", correct: true }]; expect(summarizeTrials(rows)).toMatchObject({ accuracy: .5, set_4_hit_rate: .5, set_4_false_alarm_rate: .5, set_4_k: 0 }); });
});
